## Session 6 (numpy part a)

### Basic array operations

In [1]:
import numpy as np

### Creation of different arrays using numpy

In [2]:
a = np.array([1, 3, 2, 8])
a

array([1, 3, 2, 8])

In [3]:
a = np.array([1, 3, 2, 8], dtype='float64')
a

array([1., 3., 2., 8.])

In [4]:
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.full((4, 6), 123)

array([[123, 123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123, 123]])

In [13]:
# Return a new array of given shape and type, filled with `fill_value`.
a = np.full(shape=(4, 6), fill_value=123)
a

array([[123, 123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123, 123]])

In [14]:
a[1][2]

123

In [18]:
# we can have array of multiple dimensions

# 1d
arr_1d = np.ones(4)

# 2d
arr_2d = np.ones((4, 3))

# 3d
arr_3d = np.ones((4, 3, 2))

In [24]:
print(arr_1d, end='\n \n ------------------------- \n \n')
print(arr_2d, end='\n \n ------------------------- \n \n')
print(arr_3d, end='\n \n ------------------------- \n \n')

[1. 1. 1. 1.]
 
 ------------------------- 
 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 
 ------------------------- 
 
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
 
 ------------------------- 
 


In [30]:
arr_3d[2][2][1]

1.0

In [31]:
# Return evenly spaced values within a given interval.
# (start, stop, step)
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
np.arange(5, 20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
np.arange(5, 20, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
# Return evenly spaced numbers over a specified interval.
# Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`].
# (start, stop, num)
np.linspace(0, 1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [35]:
# Return random floats in the half-open interval [0.0, 1.0).
np.random.random(4)

array([0.47750918, 0.36899676, 0.43846608, 0.25516576])

In [37]:
np.random.random((4, 3))

array([[0.45193806, 0.17052513, 0.24772271],
       [0.95325172, 0.5145713 , 0.52204182],
       [0.09357026, 0.63672881, 0.9653966 ],
       [0.24244893, 0.12082582, 0.42120812]])

In [38]:
# uniform(low=0.0, high=1.0, size=None)
# Draw samples from a uniform distribution.
# Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high).
np.random.uniform(0, 10, (4, 3))

array([[5.25158682, 2.62720123, 1.73482045],
       [1.09264134, 2.93351339, 5.45483418],
       [7.05028306, 5.5289178 , 8.80711323],
       [9.16967306, 6.19060393, 6.7245199 ]])

In [39]:
# normal(loc=0.0, scale=1.0, size=None)
# loc = Mean ("centre"), scale = Standard deviation (spread or "width")
# Draw random samples from a normal (Gaussian) distribution.
np.random.normal(1000, 50, (2, 2))

array([[ 965.32149642, 1045.93691752],
       [ 962.86154685, 1015.69399372]])

## Session 6 (numpy part b)

### Accessing array items

In [43]:
x = np.array([4, 8, 1, 3, 9, 5])
y = np.array([[5, 9, 3, 1], 
              [6, 4, 3, 9],
              [1, 7, 8, 3]])

x, y

(array([4, 8, 1, 3, 9, 5]),
 array([[5, 9, 3, 1],
        [6, 4, 3, 9],
        [1, 7, 8, 3]]))

In [44]:
x[2]

1

In [46]:
x[-2]

9

In [47]:
y[2][1]

7

In [49]:
y[2,1]

7

In [50]:
y[2,-1]

3

### Slicing

In [55]:
# slicing --> x[start:stop:step]  * stop is excluded from the result set
# * in case of absence of the three params --> start : beginning of the range
#                                                stop  : end of the range
#                                                step  : is 1
# * in case of negative values --> start & stop : is considered from the end of the range
#                                    step         : is reversed

In [56]:
x = np.array([4, 8, 1, 3, 9, 5, 11, 6, 2])

In [57]:
x[1:6:2]

array([8, 3, 5])

In [58]:
x[1:6]

array([8, 1, 3, 9, 5])

In [59]:
x[:4]

array([4, 8, 1, 3])

In [60]:
x[3::2]

array([3, 5, 6])

In [61]:
x[::-1]

array([ 2,  6, 11,  5,  9,  3,  1,  8,  4])

In [62]:
x[-4:-1:1]

array([ 5, 11,  6])

In [65]:
x[-2:-7:-1]

array([ 6, 11,  5,  9,  3])

In [69]:
x[1:-1:2]

array([8, 3, 5, 6])

In [71]:
x[:]

array([ 4,  8,  1,  3,  9,  5, 11,  6,  2])

In [67]:
# slicing of multi-dimensional arrays

In [72]:
y = np.array([[5, 9, 3, 1, 4], 
              [6, 4, 3, 9, 1],
              [1, 7, 8, 3, 12],
              [11, 8, 6, 1, 9]])

In [73]:
y[1:3,1:4]

array([[4, 3, 9],
       [7, 8, 3]])

In [78]:
y[::2,::2]

array([[ 5,  3,  4],
       [ 1,  8, 12]])

In [79]:
y[::-1,::]

array([[11,  8,  6,  1,  9],
       [ 1,  7,  8,  3, 12],
       [ 6,  4,  3,  9,  1],
       [ 5,  9,  3,  1,  4]])

In [84]:
# important tip --> numpy slicing gives us a VIEW of the original array in contrast to the
#                   python standard slicing which gives us a COPY of that.
# which means in numpy slicing, any change to the view, also applies to the original array

In [80]:
print(y)

[[ 5  9  3  1  4]
 [ 6  4  3  9  1]
 [ 1  7  8  3 12]
 [11  8  6  1  9]]


In [81]:
z = y[2:,:2]
print(z)

[[ 1  7]
 [11  8]]


In [82]:
z[0,0] = 1000
print(z)

[[1000    7]
 [  11    8]]


In [83]:
print(y)

[[   5    9    3    1    4]
 [   6    4    3    9    1]
 [1000    7    8    3   12]
 [  11    8    6    1    9]]


In [85]:
# from above code output we see that the modification of z array, also applies to y

In [86]:
# if we would like to keep the original array unchanged, we can get a copy of that

In [88]:
t = y[0:2,0:2].copy()
t

array([[5, 9],
       [6, 4]])

In [90]:
t[0,0] = 1000
t

array([[1000,    9],
       [   6,    4]])

In [92]:
y

array([[   5,    9,    3,    1,    4],
       [   6,    4,    3,    9,    1],
       [1000,    7,    8,    3,   12],
       [  11,    8,    6,    1,    9]])

### Reshaping

In [124]:
a = np.array([6, 11, 9, 4, 3, 1, 2, 5, 17])
print(a)

[ 6 11  9  4  3  1  2  5 17]


In [125]:
a.shape

(9,)

In [126]:
# note that this method doesn't change the original array
# it sometimes returns view and sometimes copy of the array
# the new shape must match the array size (i.e. in our case, array of size 9 can reshape in to (3, 3), but
# if array size was 10, then reshaping will raise an error.)
a.reshape(3, 3)

array([[ 6, 11,  9],
       [ 4,  3,  1],
       [ 2,  5, 17]])

In [127]:
a

array([ 6, 11,  9,  4,  3,  1,  2,  5, 17])

In [128]:
b = a.reshape(1, 9)

In [129]:
print(a)

[ 6 11  9  4  3  1  2  5 17]


In [130]:
print(b)

[[ 6 11  9  4  3  1  2  5 17]]


In [131]:
c = a[np.newaxis, :]
print(c)

[[ 6 11  9  4  3  1  2  5 17]]


In [137]:
a.reshape(9, 1)

array([[ 6],
       [11],
       [ 9],
       [ 4],
       [ 3],
       [ 1],
       [ 2],
       [ 5],
       [17]])

In [138]:
c2 = a[:, np.newaxis]
print(c2)

[[ 6]
 [11]
 [ 9]
 [ 4]
 [ 3]
 [ 1]
 [ 2]
 [ 5]
 [17]]


In [117]:
a = np.array([6, 11, 9, 4, 3, 1, 2, 5, 17, 3, 1, 6])

In [119]:
a.reshape(2, 6)

array([[ 6, 11,  9,  4,  3,  1],
       [ 2,  5, 17,  3,  1,  6]])

In [120]:
# for (i)D dimensional array we could only give the reshape method constructor only (i-1)D params,
# the other value will be calculated by method automatically based on the size of the array.
# note that we have to give -1 for the missing value
a.reshape(-1, 6)

array([[ 6, 11,  9,  4,  3,  1],
       [ 2,  5, 17,  3,  1,  6]])

In [121]:
a.reshape(2, 2, 3)

array([[[ 6, 11,  9],
        [ 4,  3,  1]],

       [[ 2,  5, 17],
        [ 3,  1,  6]]])

In [122]:
a.reshape(2, -1, 3)

array([[[ 6, 11,  9],
        [ 4,  3,  1]],

       [[ 2,  5, 17],
        [ 3,  1,  6]]])